#!/bin/bash

function push_image_to_registry()
{
    local imageWithTag=${IMAGE_WITH_TAG}
    docker push ${imageWithTag}
}

PROJECT=demo
FULL_PROJECT=crystallcx/${PROJECT}
DOCKER_REPO=${FULL_PROJECT}
IMAGE_WITH_TAG=${DOCKER_REPO}:latest
