name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.image2built.outputs.test }}

    steps:
    - uses: actions/checkout@v3
    - name: make ssh dir
      run: mkdir ~/.ssh/
    - name: pass in ssh private key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
    - name: start ssh agent & add ssh key to ssh agent
      run: eval $(ssh-agent -s) && chmod 400 ~/.ssh/id_rsa && ssh-add ~/.ssh/id_rsa
      
    # - name: build docker image 1 
    #   run: cd docker-images/env-cpp && ./build.sh

    - name: build docker image 2
      run: cd docker-images/ssh-in-docker && ./build.sh
      # run: eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa && cd docker-images/ssh-in-docker && ./build.sh



  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-known-hosts: 'github.com'
        persist-credentials: true
        clean: false

    - name: build & push docker image 2 
      uses: mr-smithers-excellent/docker-build-push@v5
      with: 
        image: crystallcx/demo
        dockerfile: docker-images/ssh-in-docker/Dockerfile
        registry: docker.io
        tags: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        enableBuildKit: true